# Generated by Django 5.0.6 on 2025-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('form', 'form'), ('rule', 'rule'), ('workflow', 'workflow')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('scope', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(default='published', max_length=20)),
                ('spec', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('kind', 'name', 'version')},
            },
        ),
    ]
