# Generated by Django 5.0.7 on 2025-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('tenant_id', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'patient'], name='clinical_do_tenant__01171b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'created_at'], name='clinical_do_tenant__6b981c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant_id', 'external_id'], name='clinical_pa_tenant__c43c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant_id', 'created_at'], name='clinical_pa_tenant__00c20c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['tenant_id', 'created_at'], name='clinical_vi_tenant__187669_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['tenant_id', 'patient'], name='clinical_vi_tenant__9a7b83_idx'),
        ),
    ]
