# Generated by Django 5.0.7 on 2025-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_document_created_at_document_tenant_id_and_more'),
    ]

    operations = [
    ]
