# Generated by Django 5.0.7 on 2025-09-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_auto_20250919_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_consent', 'Pending Consent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['tenant_id', 'status'], name='clinical_vi_tenant__b40d89_idx'),
        ),
    ]
