# Generated by Django 5.0.7 on 2025-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('form', 'Form'), ('rule', 'Rule'), ('workflow', 'Workflow')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('scope', models.CharField(default='global', max_length=100)),
                ('spec_json', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('kind', 'name', 'version', 'scope')},
            },
        ),
    ]
