# Generated by Django 5.0.7 on 2025-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('tenant_id', 'kind', 'name', 'version', 'scope')},
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['tenant_id', 'kind', 'name', 'status'], name='configurato_tenant__bdf448_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['tenant_id', 'created_at'], name='configurato_tenant__a08e7d_idx'),
        ),
    ]
