# Generated by Django 5.0.7 on 2025-09-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_config_unique_together_config_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='tenant_id',
            field=models.CharField(max_length=100, db_index=True, help_text='Tenant identifier', default='DEV'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('tenant_id', 'kind', 'name', 'version', 'scope')},
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['tenant_id', 'kind', 'name', 'status'], name='configurator_config_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['tenant_id', 'created_at'], name='configurator_config_tenant_created_idx'),
        ),
    ]
