# Generated by Django 4.2.24 on 2025-09-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20250918_2359'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='config',
            name='configurator_config_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='config',
            name='configurator_config_tenant_created_idx',
        ),
    ]
