# Generated by Django 5.0.7 on 2025-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
    ]
