# Generated by Django 5.0.7 on 2025-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Tenant identifier', max_length=100)),
                ('version', models.IntegerField(default=1, help_text='Policy version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('resource_type', models.CharField(choices=[('field', 'Field'), ('record', 'Record'), ('workflow', 'Workflow'), ('workflow_step', 'Workflow Step')], max_length=20)),
                ('action', models.CharField(help_text='Action (read, write, execute, publish, etc.)', max_length=50)),
                ('selector', models.JSONField(default=dict, help_text='Resource selector criteria')),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('condition', models.TextField(blank=True, help_text='Optional condition expression', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'unique_together': {('tenant_id', 'version', 'status')},
            },
        ),
    ]
