# Generated by Django 5.0.7 on 2025-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outbox',
            name='tenant_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant_id',
            field=models.CharField(db_index=True, default=0, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'status'], name='orchestrato_tenant__3b76a0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'created_at'], name='orchestrato_tenant__f3cdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['tenant_id', 'published'], name='orchestrato_tenant__b20353_idx'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['tenant_id', 'created_at'], name='orchestrato_tenant__9604aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'status'], name='orchestrato_tenant__171ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'due_at'], name='orchestrato_tenant__9399b8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'created_at'], name='orchestrato_tenant__03c03f_idx'),
        ),
    ]
