# Generated by Django 5.0.7 on 2025-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_notification_tenant_id_notification_updated_at_and_more'),
    ]

    operations = [
    ]
