# Generated by Django 5.0.7 on 2025-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant identifier', max_length=100)),
                ('limits_json', models.JSONField(default=dict, help_text='JSON object defining quota limits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id',)},
            },
        ),
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month')], max_length=20)),
                ('metric', models.CharField(help_text='Metric being tracked', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['tenant_id', 'period', 'metric'], name='quotas_tena_tenant__5b9a29_idx'), models.Index(fields=['tenant_id', 'window_start'], name='quotas_tena_tenant__d95cd0_idx')],
                'unique_together': {('tenant_id', 'period', 'metric', 'window_start')},
            },
        ),
    ]
