# Generated by Django 5.0.7 on 2025-09-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('share', 'Share'), ('export', 'Export'), ('delete', 'Delete')], max_length=20)),
                ('resource', models.CharField(help_text='Resource being accessed', max_length=200)),
                ('fields', models.JSONField(default=list, help_text='Fields accessed/modified')),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('ops', 'Operations'), ('research', 'Research'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('emergency', 'Emergency')], max_length=50)),
                ('data_categories', models.JSONField(default=list, help_text='Data categories involved')),
                ('consent_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('event_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for decision')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', 'patient_id', 'timestamp'], name='consent_aud_tenant__98b30c_idx'), models.Index(fields=['tenant_id', 'action', 'timestamp'], name='consent_aud_tenant__1ad7b9_idx'), models.Index(fields=['tenant_id', 'decision', 'timestamp'], name='consent_aud_tenant__e876ae_idx'), models.Index(fields=['tenant_id', 'consent_id'], name='consent_aud_tenant__83a4ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('ops', 'Operations'), ('research', 'Research'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('emergency', 'Emergency')], max_length=50)),
                ('data_categories', models.JSONField(default=list, help_text='List of data categories covered by this consent')),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending')], default='granted', max_length=20)),
                ('notice_lang', models.CharField(default='en', max_length=10)),
                ('withdraw_url', models.URLField(blank=True, null=True)),
                ('abdm_artefact_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('consent_method', models.CharField(default='digital', help_text='How consent was obtained', max_length=50)),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('legal_basis', models.CharField(default='consent', help_text='Legal basis for processing', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='consent_con_tenant__57b4dc_idx'), models.Index(fields=['tenant_id', 'purpose'], name='consent_con_tenant__2cc91c_idx'), models.Index(fields=['tenant_id', 'status'], name='consent_con_tenant__10ce3a_idx'), models.Index(fields=['tenant_id', 'expiry'], name='consent_con_tenant__fe1be1_idx')],
                'unique_together': {('tenant_id', 'consent_id')},
            },
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('ops', 'Operations'), ('research', 'Research'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('emergency', 'Emergency')], max_length=50)),
                ('data_categories', models.JSONField(default=list)),
                ('abdm_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('abdm_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consent.consent')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'patient_id'], name='consent_con_tenant__abc0e1_idx'), models.Index(fields=['tenant_id', 'status'], name='consent_con_tenant__5083d6_idx'), models.Index(fields=['tenant_id', 'expires_at'], name='consent_con_tenant__f2499c_idx')],
            },
        ),
    ]
