# Generated by Django 5.0.7 on 2025-09-18 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hook', 'Extension Hook'), ('subscription', 'Event Subscription'), ('webhook', 'Workflow Webhook')], max_length=50)),
                ('target', models.CharField(help_text='Target URL or identifier', max_length=200)),
                ('payload_json', models.JSONField(default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('runtime.compute', 'Runtime Compute'), ('runtime.validate', 'Runtime Validate')], max_length=20)),
                ('match_json', models.JSONField(default=dict, help_text="Matching criteria, e.g. {'form': 'visit_opd'}")),
                ('invoke_json', models.JSONField(default=dict, help_text='Invocation config: {method, url, timeout_ms, headers}')),
                ('secret', models.CharField(help_text='HMAC secret for signing requests', max_length=200)),
                ('retries', models.IntegerField(default=3)),
                ('cache_ttl_s', models.IntegerField(blank=True, help_text='Cache TTL in seconds, null for no cache', null=True)),
                ('is_blocking', models.BooleanField(default=False, help_text='If True, failures block the main flow')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phase', models.CharField(choices=[('submission.pre', 'Pre Submission'), ('submission.post', 'Post Submission')], max_length=20)),
                ('match_json', models.JSONField(default=dict, help_text='Matching criteria')),
                ('invoke_json', models.JSONField(default=dict, help_text='Invocation config')),
                ('secret', models.CharField(help_text='HMAC secret for signing requests', max_length=200)),
                ('retries', models.IntegerField(default=3)),
                ('is_blocking', models.BooleanField(default=False, help_text='If True, failures block submission')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('topics', models.JSONField(default=list, help_text='List of topics to subscribe to')),
                ('endpoint', models.URLField(max_length=500)),
                ('secret', models.CharField(help_text='HMAC secret for signing requests', max_length=200)),
                ('retries', models.IntegerField(default=3)),
                ('dead_letter', models.BooleanField(default=True, help_text='Send failed messages to dead letter queue')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
