# Generated by Django 5.0.7 on 2025-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('form_name', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(default='received', max_length=50)),
                ('errors_json', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
