# Generated by Django 5.0.7 on 2025-09-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='tenant_id',
            field=models.CharField(db_index=True, default=0, help_text='Tenant identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='idempotency_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('tenant_id', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant_id', 'form_name'], name='submission__tenant__9cbb65_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant_id', 'created_at'], name='submission__tenant__c76153_idx'),
        ),
    ]
